# Generated by Django 2.0.2 on 2018-12-04 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='emailid',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='fname',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
