# Generated by Django 2.0.2 on 2018-12-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181204_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
